import 'package:get/get.dart';

class LocaleStrings extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'OnlineStore': 'OnlineStore',
          'Add to cart': 'Add to cart',
          'Search in OnlineStore': 'Search in OnlineStore',
          'Buy Now': 'Buy Now',
          'Details': 'Details',
          'Logout': 'Logout',
          'Are you sure you want to log out?': 'Are you sure you want to log out?',
          'Yes': 'Yes',
          'No': 'No',
          'User Name': 'User Name',
          'Password': 'Password',
          'Login': 'Login',
          'skip': 'skip',
          'English': 'English',
          'Nepali': 'Nepali',
          'Select Language': 'Select Language',
          'Added to Cart': 'Added to Cart',
          'added to the cart': 'added to the cart',
          'Already in Cart': 'Already in Cart',
          'is already in your cart': 'is already in your cart',
          'Mycart': 'Mycart',
          'cart is empty': 'cart is empty',
          'No such products found': 'No such products found',
          'Removed from Cart': 'Removed from Cart',
          'removed from the cart': 'removed from the cart',
        },
        'ne_NE': {
          'OnlineStore': 'अनलाइन स्टोर',
          'Add to cart': 'थप्नुहोस् कार्ट मा',
          'Search in OnlineStore': 'अनलाइन स्टोर मा खोज्नुहोस्',
          'Buy Now': 'अहिले खरिद गर्नु',
          'Details': 'विवरण',
          'Logout': 'लग आउट',
          'Are you sure you want to log out?': 'के तपाई लग आउट गर्न निश्चित हुनुहुन्छ?',
          'Yes': 'हो',
          'No': 'छैन',
          'User Name': 'प्रयोगकर्ता नाम',
          'Password': 'पासवर्ड',
          'Login': 'लग-इन',
          'skip': 'छोड्नुहोस्',
          'English': 'अंग्रेजी',
          'Nepali': 'नेपाली',
          'Select Language': 'भाषा छनोट गर्नुहोस्',
          'Added to Cart': 'कार्टमा थपियो',
          'added to the cart': 'कार्टमा थपियो',
          'Already in Cart': 'कार्टमा पहिले नै उपलब्ध छ',
          'is already in your cart': 'कार्टमा पहिले नै उपलब्ध छ',
          'Mycart': 'मेरो कार्ट',
          'cart is empty': 'कार्ट खाली छ',
          'No such products found': 'फेला परेन',
          'Removed from Cart': 'कार्टबाट हटाइयो',
          'removed from the cart': 'कार्टबाट हटाइयो',
        },
      };
}
